### ISSUE TITLE
Icons didn't shows properly.

### ISSUE THREAD

**Issue by CH1ef** [jordonwow/omnibar#10]
After 8.1 there is gabs between icons. Also when spell used he didn't moves to left side (Pos1), he stays in same position where it was before use.
Screenshot below. 
http://prntscr.com/luh05r

**Comment by Gee19** [comment]
There is an option to adjust padding

**Comment by CH1ef** [comment]
> There is an option to adjust padding

When this screenshot was made padding was set to 0. This is not settings problem for sure.
