### ISSUE TITLE
Works in test, but not game

### ISSUE THREAD

**Issue by rosenberger877** [jordonwow/omnibar#100]
I'm trying to track Paladin Divine Shield as bubble animation doesnt show up well on my screen. Set it up on Omnibar as both a spell and interrupt. When I test it works but it doesnt work on duels or Battlegrounds. Please help

**Comment by rosenberger877** [comment]
I can get an icon for divine shield to show up if I check the Interrupt spell name. Unfortunately, it measure the cooldown of my opponent which is 5 minutes until his divine shield comes back, not the 8 seconds the bubble is up

**Comment by rosenberger877** [comment]
I want to know when bubble is up then when it is down

**Comment by briceburg** [comment]
> I'm trying to track Paladin Divine Shield as bubble animation doesnt show up well on my screen. Set it up on Omnibar as both a spell and interrupt. When I test it works but it doesnt work on duels or Battlegrounds. Please help

curios -- what do you use for your "test" setupo? I wanted to try some addon development and am completely new to the game...

**Comment by jordonwow** [comment]
Please reopen if you experience this issue in v12.0
