### ISSUE TITLE
Omni bar hasnt worked for months??

### ISSUE THREAD

**Issue by WEEZYPEANUT** [jordonwow/omnibar#108]
iv tried re installing and that doesnt work, it works fine in test mode but inside any arena its stoped working and its been that way for months now, pretty much all of 2021 when can we get a update for this?

**Comment by WEEZYPEANUT** [comment]
iv also disabled all addons except gladius and dominos and omnibar and it still wont show... ?

**Comment by jordonwow** [comment]
reopen if you're still having issues with the latest version and post any errors
