### ISSUE TITLE
Omnibar issues persisting for months now, similar to the other issue right below mine

### ISSUE THREAD

**Issue by jramsey021** [jordonwow/omnibar#110]
I have 4 different bars set up to track kicks, cc, defensives, and offensives and after an update maybe 2 or 3 releases ago they just all stopped working. I haven't changed any of my settings, and a prior release completely busted Omnibar for me and not even a re-install fixed it.

After a recent update 2 of the bars just randomly started working. Each bar shares the same settings in terms of visibility, etc, with the only differences being the direction rows grow and which spells are displayed.

Everything displays properly when I click the test button, but once I enter an arena the only bars that work are kicks and cc's... I can not see the defensive or offensive bars.
![omnibar](https://user-images.githubusercontent.com/10729492/114059778-b7097780-9862-11eb-8a05-2db22d9aeb5c.png)

**Comment by LukaLopotar** [comment]
Please check if you have under "Units" tab checkmark on "Enable all enemies", "Enable arena 1", "Enable arena 2", "Enable arena 3". That could be the source of your problem.
![WoWScrnShot_041121_213157_cut](https://user-images.githubusercontent.com/38010971/114318620-235bd380-9b0e-11eb-8864-5aa91f408e90.jpg)
![WoWScrnShot_041121_213203_cut](https://user-images.githubusercontent.com/38010971/114318621-2951b480-9b0e-11eb-8347-fb4942a7c950.jpg)
![WoWScrnShot_041121_213204_cut](https://user-images.githubusercontent.com/38010971/114318627-2bb40e80-9b0e-11eb-810e-a1fc0717feb3.jpg)
![WoWScrnShot_041121_213205_cut](https://user-images.githubusercontent.com/38010971/114318628-2d7dd200-9b0e-11eb-8cf4-ce81277a691a.jpg)

**Comment by waguto** [comment]
Are you tracking just arena? Mine wasn't showing... what I did was checking all "enable arena" boxes (like the post above shows) and UNCHECKING the "All Enemies" box option. It is tracking now, but I only track stuff in arena. Hope it helps!

**Comment by jramsey021** [comment]
The above comment was what ended up resolving my issue. No idea what happened, but after some update apparently some of the Units got unchecked. Still not sure exactly what caused the problem, but I had set everything up when I first installed OmniBar and it worked fine until some settings got unchecked after some update and I didn't even know the settings existed.
