### ISSUE TITLE
Unused spells only appear after enemy cast them

### ISSUE THREAD

**Issue by Destina96** [jordonwow/omnibar#117]
Unused spells only appear after the enemy cast them if you select any units other than "All enemies" . If you select arena 1 - 2 - 3 spells dont show until they use them even if you select "Show unused icons"

![Screenshot_3](https://user-images.githubusercontent.com/84405391/118695024-63049200-b815-11eb-9e2e-9a49cb53cb32.png)
![Screenshot_4](https://user-images.githubusercontent.com/84405391/118695032-64ce5580-b815-11eb-8804-f6fff1f5f8b0.png)
![Screenshot_1](https://user-images.githubusercontent.com/84405391/118695083-74e63500-b815-11eb-8798-61fcc2cfd550.png)

**Comment by void-ow** [comment]
Can attest to that one as well, would be super great if that'll be fixed. Thank you!
