### ISSUE TITLE
Wrong spells

### ISSUE THREAD

**Issue by Destina96** [jordonwow/omnibar#119]
Why i see other spec spells in my omnibar ?
![Screenshot_2](https://user-images.githubusercontent.com/84405391/118889372-b524e080-b905-11eb-95f1-2c1c7ff1244a.png)
![Screenshot_3](https://user-images.githubusercontent.com/84405391/118889455-d1c11880-b905-11eb-9c99-fc469195e8e0.png)

**Comment by Destina96** [comment]
Am i the only one who see offspec spells in omnibar?

**Comment by jordonwow** [comment]
Please reopen if you experience this issue in v12.0
