### ISSUE TITLE
new update creates and duplicates raidframes 

### ISSUE THREAD

**Issue by RyanMccaffrey** [jordonwow/omnibar#121]
After updating it suddenly created raidframes covering my whole screen. Is at least caused by this addon. Startss/stops when I enable/disable it.

![image](https://user-images.githubusercontent.com/3332236/118898811-69f5d800-b8db-11eb-8086-e94121ace524.png)

**Comment by sod** [comment]
I also got issues with my unitframes after the update. My addon pitbul becomes super slow and auras aren't rendered anymore. As soon as I disable omnibar, it works again.

**Comment by jordonwow** [comment]
Please reopen if you experience this issue in v12.0
