### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by VincentEngel** [jordonwow/omnibar#123]
German client fighting against a russian mage.

Lua error:

`Message: Interface\AddOns\OmniBar\OmniBar.lua:538: attempt to index field '?' (a number value)
Time: Mon May 24 15:44:17 2021
Count: 3
Stack: Interface\AddOns\OmniBar\OmniBar.lua:538: attempt to index field '?' (a number value)
[string "@Interface\AddOns\OmniBar\OmniBar.lua"]:538: in function <Interface\AddOns\OmniBar\OmniBar.lua:521>

Locals: self = OmniBar1 {
 0 = <userdata>
 specs = <table> {
 }
 disabled = false
 active = <table> {
 }
 icons = <table> {
 }
 zone = "pvp"
 detected = <table> {
 }
 cooldowns = <table> {
 }
 key = "OmniBar1"
 BASE_ICON_SIZE = 36
 anchor = OmniBar1Anchor {
 }
 numIcons = 50
 settings = <table> {
 }
 container = OmniBar1Icons {
 }
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
_ = 1621863857.023000
subEvent = "SPELL_CAST_SUCCESS"a`

**Comment by VincentEngel** [comment]
Similar Error while playing against another undead mage. I think it might happend the moment he used Cold Snap.

`Message: Interface\AddOns\OmniBar\OmniBar.lua:538: attempt to index field '?' (a number value)
Time: Tue May 25 19:10:27 2021
Count: 1
Stack: Interface\AddOns\OmniBar\OmniBar.lua:538: attempt to index field '?' (a number value)
[string "@Interface\AddOns\OmniBar\OmniBar.lua"]:538: in function <Interface\AddOns\OmniBar\OmniBar.lua:521>

Locals: self = OmniBar1 {
 0 = <userdata>
 specs = <table> {
 }
 disabled = false
 active = <table> {
 }
 icons = <table> {
 }
 zone = "pvp"
 detected = <table> {
 }
 cooldowns = <table> {
 }
 key = "OmniBar1"
 BASE_ICON_SIZE = 36
 anchor = OmniBar1Anchor {
 }
 numIcons = 50
 settings = <table> {
 }
 container = OmniBar1Icons {
 }
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
_ = 1621962627.510000
subEvent = "SPELL_CAST_SUCCESS"
_ = false
sourceGUID = "Player-4749-01B91DBE"
sourceName = "Zomby-Earthshaker"
sourceFlags = 66888
_ = 0
_ = ""
_ = nil
_ = -2147483648
_ = -2147483648
spellID = 11958
spellName = "Kälteeinbruch"
(for index) = 1
(for limit) = 5
(for step) = 1
i = 1
(for index) = 1
(for limit) = 4
(for step) = 1
j = 1
(*temporary) = 11426
(*temporary) = OmniBar1Icon5 {
 0 = <userdata>
 HotKey = OmniBar1Icon5HotKey {
 }
 TargetTexture = <unnamed> {
 }
 NewActionTexture = <unnamed> {
 }
 class = "MAGE"
 Border = OmniBar1Icon5Border {
 }
 Flash = OmniBar1Icon5Flash {
 }
 duration = 384
 added = 1131255.981000
 newitemglowAnim = <unnamed> {
 }
 spellID = 11958
 icon = OmniBar1Icon5Icon {
 }
 Name = OmniBar1Icon5Name {
 }
 AutoCastable = <unnamed> {
 }
 SpellHighlightAnim = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 FocusTexture = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 SpellHighlightTexture = <unnamed> {
 }
 flash = <unnamed> {
 }
 NormalTexture = OmniBar1Icon5NormalTexture {
 }
 FlyoutBorderShadow = OmniBar1Icon5FlyoutBorderShadow {
 }
 FlyoutBorder = OmniBar1Icon5FlyoutBorder {
 }
 Count = OmniBar1Icon5Count {
 }
 AutoCastShine = OmniBar1Icon5Shine {
 }
 FlyoutArrow = OmniBar1Icon5FlyoutArrow {
 }
 cooldown = OmniBar1Icon5Cooldown {
 }
 sourceGUID = "Player-4749-01B91DBE"
}
(*temporary) = nil
(*temporary) = 1131255.981000
(*temporary) = false
(*temporary) = false
(*temporary) = OmniBar1 {
 0 = <userdata>
 specs = <table> {
 }
 disabled = false
 active = <table> {
 }
 icons = <table> {
 }
 zone = "pvp"
 detected = <table> {
 }
 cooldowns = <table> {
 }
 key = "OmniBar1"
 BASE_ICON_SIZE = 36
 anchor = OmniBar1Anchor {
 }
 numIcons = 50
 settings = <table> {
 }
 container = OmniBar1Icons {
 }
}
(*temporary) = OmniBar1Icon5 {
 0 = <userdata>
 HotKey = OmniBar1Icon5HotKey {
 }
 TargetTexture = <unnamed> {
 }
 NewActionTexture = <unnamed> {
 }
 class = "MAGE"
 Border = OmniBar1Icon5Border {
 }
 Flash = OmniBar1Icon5Flash {
 }
 duration = 384
 added = 1131255.981000
 newitemglowAnim = <unnamed> {
 }
 spellID = 11958
 icon = OmniBar1Icon5Icon {
 }
 Name = OmniBar1Icon5Name {
 }
 AutoCastable = <unnamed> {
 }
 SpellHighlightAnim = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 FocusTexture = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 SpellHighlightTexture = <unnamed> {
 }
 flash = <unnamed> {
 }
 NormalTexture = OmniBar1Icon5NormalTexture {
 }
 FlyoutBorderShadow = OmniBar1Icon5FlyoutBorderShadow {
 }
 FlyoutBorder = OmniBar1Icon5FlyoutBorder {
 }
 Count = OmniBar1Icon5Count {
 }
 AutoCastShine = OmniBar1Icon5Shine {
 }
 FlyoutArrow = OmniBar1Icon5FlyoutArrow {
 }
 cooldown = OmniBar1Icon5Cooldown {
 }
 sourceGUID = "Player-4749-01B91DBE"
}
(*temporary) = "attempt to index field '?' (a number value)"
CombatLogGetCurrentEventInfo = <function> defined =[C]:-1
IsSourceHostile = <function> defined @Interface\AddOns\OmniBar\OmniBar.lua:515
spellIdByName = nil
cooldowns = <table> {
 20252 = <table> {
 }
 35389 = <table> {
 }
 1020 = <table> {
 }
 19277 = <table> {
 }
 30546 = <table> {
 }
 14266 = <table> {
 }
 1022 = <table> {
 }
 14282 = <table> {
 }
 14290 = <table> {
 }
 10230 = <table> {
 }
 17391 = <table> {
 }
 12292 = <table> {
 }
 11285 = <table> {
 }
 27685 = <table> {
 }
 2062 = <table> `

**Comment by jordonwow** [comment]
fixed in v12.0 thanks
