### ISSUE TITLE
Cooldown Reset Functionality Broken [Omnibar.lua ln 538]

### ISSUE THREAD

**Issue by bluedreamz1** [jordonwow/omnibar#125]
Attempt to index field "?" a number value

`if resets[spellID][j].spell == self.active[i].spellID then`

Related to : https://github.com/jordonwow/omnibar/issues/103

**Comment by jordonwow** [comment]
Please update to the latest release this isn't in the codebase anymore

**Comment by bluedreamz1** [comment]
roger that thank you!
