### ISSUE TITLE
attempt to call upvalue 'IsRatedBattleground' (a nil value)

### ISSUE THREAD

**Issue by wing5wong** [jordonwow/omnibar#128]
Recently started getting this many times a night when playing RBGs. (Retail WoW)
unfortunately wont be able to test without addons at this stage, but perhaps something obvious with this

`51x OmniBar\OmniBar-v12.1.lua:734: attempt to call upvalue 'IsRatedBattleground' (a nil value)`

**Comment by dinkmaster** [comment]
getting the same error in every rated BG after last update

**Comment by wing5wong** [comment]
Thanks!
