### ISSUE TITLE
having inspect issue in raid

### ISSUE THREAD

**Issue by HoMing-Ryan** [jordonwow/omnibar#130]
after the update v12.1 and v12.2, every time when i was in a raid i am having issue to inspect people, it takes about 30 to 40 seconds to load the inspect window and it wont show any gear that they are wearing
ive tested with no addons except this one

**Comment by jordonwow** [comment]
Are you getting an error related to OmniBar?

**Comment by HoMing-Ryan** [comment]
nope dont have any error popping up but the issue only happens when i have omnibar turned on

**Comment by HoMing-Ryan** [comment]
![Wow_2k9Bo6qvYg](https://user-images.githubusercontent.com/56599462/120217735-59dee080-c26b-11eb-8542-4f6c8e6654e2.png)
it looks like this

**Comment by HoMing-Ryan** [comment]
an update to the issue: after some testing, the issue only seems to happen when someone in your group is offline, regardless of in a raid or party

**Comment by allstar-uk** [comment]
@HoMing-Ryan nah that's not accurate. I'm a pvp player and all the guys I play with have the same issue, even when everyone is online.

@jordonwow Why does OmniBar trigger when inspecting a player? Definitely causing major inspect issues.

![image](https://user-images.githubusercontent.com/16060879/121437963-124b0980-c97b-11eb-9a1a-de0a9d23d668.png)

**Comment by Leenkss** [comment]
same problem
if turn off omnibar i can check players gear\pvp tab
