### ISSUE TITLE
OmniBar is showing up in WORLD PvP while it should only show up in Arena

### ISSUE THREAD

**Issue by awedy01** [jordonwow/omnibar#133]
As the title says:
OmniBar is showing up in WORLD PvP while it should only show up in Arena (i noted it twice with paladins only)
![omnibarbug](https://user-images.githubusercontent.com/57992981/120326600-32c6f400-c2e9-11eb-86d8-e34b24e01186.PNG)

**Comment by jordonwow** [comment]
Please update to v12.3
