### ISSUE TITLE
pet abilities

### ISSUE THREAD

**Issue by LilacGooseberries** [jordonwow/omnibar#141]
tbcc, russian client, cant track pet abilities (spell lock, devour, etc)
i suppose its because "local function UnitOwnerName(guid)" relies on client language?

**Comment by Bisonpasfute** [comment]
same problem here with the french client. I've added both ranks of spell lock and even though it should be displayed in arena, it isn't.

**Comment by kiximax** [comment]
i commented line 666 to workaround this xd
https://github.com/jordonwow/omnibar/blob/master/OmniBar.lua#L666

**Comment by jordonwow** [comment]
I think I fixed this issue, please reopen if it's still happening
