### ISSUE TITLE
Getting Lua error when using shamanism pvp talente

### ISSUE THREAD

**Issue by tsoxos** [jordonwow/omnibar#142]
![WoWScrnShot_071321_221945](https://user-images.githubusercontent.com/50651566/125512447-b073addf-cbee-4b32-b5c2-ea275353df9f.jpg)

Getting this error if I use shamanism pvp talent. Same if all other addons are disabled and only omnibar is enabled. Without shamanism pvp talent (Heroism) it works.

**Comment by neuvo123** [comment]
im getting this same lua error after patch with latest omnibar

Message: Interface\AddOns\OmniBar\OmniBar.lua:682: attempt to index field '?' (a nil value)
Time: Wed Jul 14 18:52:40 2021
Count: 6
Stack: Interface\AddOns\OmniBar\OmniBar.lua:682: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\OmniBar\OmniBar.lua"]:682: in function `AddSpellCast'
[string "@Interface\AddOns\OmniBar\OmniBar.lua"]:728: in function `?'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
