### ISSUE TITLE
[Wrath] Shared Cooldowns

### ISSUE THREAD

**Issue by rollerskates80** [jordonwow/omnibar#167]
Some abilities are not properly sharing a cooldown. Specifically:

- Hunter: Freezing Arrow, Freezing Trap
- Warrior: Recklessness/Shield Wall/Retaliation (all share 12 second CD)
- Paladin: Avenging Wrath cast incurs 30 sec cooldown on Divine Protection, Divine Shield, Lay on Hands

**Comment by jordonwow** [comment]
Thanks! 2adbe039a216958772cceae4356b28f04fde1ae2
