### ISSUE TITLE
DF Pre-Patch - Omnibar Loads but each icon has a square around it.

### ISSUE THREAD

**Issue by Nellielex** [jordonwow/omnibar#171]
As the title mentions, Omnibar loads in the DF Pre-Patch. However, each CD has a large square/anchor around it.

![image](https://user-images.githubusercontent.com/116826826/198334533-a94de65e-3952-490f-b675-03c04d74c851.png)

**Comment by Nik1536** [comment]
everyone iknow is having this same issue.. including me.
