### ISSUE TITLE
Pet kicks not tracking

### ISSUE THREAD

**Issue by ekubo123** [jordonwow/omnibar#18]
DK and warlock pet kicks are not tracking in my omnibar and havent been for a few weeks.

I have leap and shambling rush tracker for dks and  it is not showing up at all but I also have dark transformation tracking and that tracks the cd properly.

I have call felhunter tracking for warlock and that cd never tracks when a warlock uses it.

**Comment by jordonwow** [comment]
Please let me know if this is still happening in the latest version

**Comment by antisnake123** [comment]
2026 and still having this issue
