### ISSUE TITLE
Omnibar installed, not appearing in game.

### ISSUE THREAD

**Issue by dragynbeats** [jordonwow/omnibar#23]
I have Omnibar installed, and I can see it in my add-on list. However, when I load into the game, it will never show up. The add-on is enabled when I log in but the /ob command doesn't work and it doesn't give me an error either. I have tried reinstalling it but nothing seems to work. Am I destined to play WoW without Omnibar, or is there some obvious fix I am missing?

**Comment by espenja** [comment]
Go to your folder equivalent to this on my computer:
`D:\World of Warcraft\_retail_\WTF\Account\AccountName\SavedVariables`

_Be warned: This will wipe any settings you had in OmniBar, but it will make it appear again_

1. Exit World of Warcraft (Important)
2. Delete `OmniBar.lua` in the folder mentioned above

Hope it works! :)

**Comment by Bluedream617** [comment]
I was having the same problems as Dragynbeats, this helped me thank you so much!

**Comment by Garciapriest** [comment]
Hello,

I have the same problem but removing the Omnibar.lua didnt solve my problem. I tried to install it from curse, manually, deleting the .lua, nothing works

**Comment by Garciapriest** [comment]
still didnt find a way to get it running ingame

**Comment by Fanttom88** [comment]
Same problem here, and i think it happend after i tryed Classic test... I tryed delete OmniBar.lua . Reinstaled more than 20 times lol and still nothing.

**Comment by Fanttom88** [comment]
Ok i fixed the problem after 2 days... 
You need to delete also Omnibar script from 
D:\World of Warcraft\_retail_\WTF\Account\AccountName\SavedVariables  (Not only the  OmniBar.lua)

**Comment by jordonwow** [comment]
Please let me know if this issue still exists in the latest version
