### ISSUE TITLE
LuaError : Interface\AddOns\OmniBar\Options.lua:108

### ISSUE THREAD

**Issue by LTTi** [jordonwow/omnibar#27]
Message: Interface\AddOns\OmniBar\Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
Time: Wed Oct  2 19:41:12 2019
Count: 1
Stack: Interface\AddOns\OmniBar\Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
(tail call): ?
[C]: in function `error'
Interface\FrameXML\ObjectAPI\Spell.lua:51: in function `ContinueOnSpellLoad'
Interface\AddOns\OmniBar\Options.lua:108: in function <Interface\AddOns\OmniBar\Options.lua:53>
Interface\AddOns\OmniBar\Options.lua:557: in function `AddBarToOptions'
Interface\AddOns\OmniBar\OmniBar.lua:107: in function <Interface\AddOns\OmniBar\OmniBar.lua:70>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:491: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1210: in function <Interface\FrameXML\UIParent.lua:1106>

Locals: <none>

**Comment by mr-aleks** [comment]
same
![image](https://user-images.githubusercontent.com/23143866/66055164-cb6a0700-e53d-11e9-8bc9-11159b536f01.png)

**Comment by jordonwow** [comment]
Fixed thanks
