### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by bostjansn** [jordonwow/omnibar#28]
I tried everything, uninstall download again, uninstall twich as much as possible to make it work, but it does not appear in the game or the configuration (/ ob) if it appears in accessories

**Comment by jordonwow** [comment]
Please post your BigDebuffs.lua file found in `WTF/Account/YOUR ACCOUNT/SavedVariables`

**Comment by bostjansn** [comment]
in this link I uploaded the file [https://mega.nz/#F!q0sHnQBK!C85Xwmy6XlBHOB5jgyCrOg](url)

**Comment by jordonwow** [comment]
So sorry, I meant OmniBar.lua. Please do the same for that file

**Comment by bostjansn** [comment]
[https://mega.nz/#F!q0sHnQBK!C85Xwmy6XlBHOB5jgyCrOg](url)

**Comment by jordonwow** [comment]
Okay I found the error and fixed it, please update to v10.3
