### ISSUE TITLE
Can't open options with slash command

### ISSUE THREAD

**Issue by Wyveryx** [jordonwow/omnibar#29]
4x OmniBar\OmniBar-v10.3.lua:93: attempt to call method 'Initialize' (a nil value)
OmniBar\OmniBar-v10.3.lua:93: in function <OmniBar\OmniBar.lua:70>
[C]: ?
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:380: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:695: in function <FrameXML\UIParent.lua:658>
[C]: ?

**Comment by jordonwow** [comment]
Looks like a conflict with another addon. Whatever addon `...ceAdiBags` is might have an outdated AceAddon version. Could you post a list of the addons you use or try disabling that one?

**Comment by Wyveryx** [comment]
I'll try disabling, my list is long lol

**Comment by Wyveryx** [comment]
well disabling didn't take care of it...
I went on a different character and disabled all but OmniBar and ACP (Addon Control Panel), and Buggrabber and Bugsack....

These are the errors I am getting...


> 6x OmniBar\OmniBar-v10.3.lua:170: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
OmniBar\OmniBar-v10.3.lua:170: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1


> 7x OmniBar\OmniBar-v10.3.lua:93: attempt to call method 'Initialize' (a nil value)
OmniBar\OmniBar-v10.3.lua:93: in function <OmniBar\OmniBar.lua:70>
[C]: ?
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:380: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:695: in function <FrameXML\UIParent.lua:658>
[C]: ?


Anything related to Atlas has been disabled from the login screen, and I even disabled ACP, so there wouldn't be any possibility of preloaded info...

**Comment by jordonwow** [comment]
Please reopen if you still have this issue with the latest version v10.5
