### ISSUE TITLE
Omnibar not allowing me to add custom spells

### ISSUE THREAD

**Issue by Rapidsxd** [jordonwow/omnibar#30]
Trying to add war banner and dispels to omnibar. When i go to custom spells and put the spell id in it shows the ability and says spell id 527 and delete under. it doesnt say what the ability does or allow me to edit anything. 
Adding a picture as well. I have tried to uninstall and reinstall but it doesnt fix the issue. Would love some help!

![WoWScrnShot_101119_231611](https://user-images.githubusercontent.com/56464144/66694799-2659d780-ec7d-11e9-8e3f-697c8e87410e.jpg)

**Comment by jordonwow** [comment]
Please send me your `OmniBar.lua` file found in `WTF/Account/YOUR ACCOUNT/SavedVariables`

**Comment by Rapidsxd** [comment]
[OmniBar.zip](https://github.com/jordonwow/omnibar/files/3722189/OmniBar.zip)

**Comment by Rapidsxd** [comment]
[OmniBar FROM ACC.zip](https://github.com/jordonwow/omnibar/files/3722514/OmniBar.FROM.ACC.zip)

Sorry sent the wrong one. Here is correct one

**Comment by sylv3r** [comment]
Same issue here, adding spells in the "Custom Spells" tab does not seem to add anything to the bar and there's no option to do anything with it.

**Comment by Verlo44** [comment]
Hello i have the exactly the same problem. Wow classic version. Thanks

**Comment by jordonwow** [comment]
Fixed in latest version
