### ISSUE TITLE
/ob doesn't do anything

### ISSUE THREAD

**Issue by Lintujr** [jordonwow/omnibar#31]
I can see the Omnibar in the left corner @ character selection, but ingame the command does nothing. I also can't find it by going Interface > Addons.

**Comment by jordonwow** [comment]
Please send me your `OmniBar.lua` file found in `WTF/Account/YOUR ACCOUNT/SavedVariables`

**Comment by Lintujr** [comment]
OmniBarDB = {
	["profileKeys"] = {
		["Testlintu - Dragonfang"] = "Default",
		["Lintu - Firemaw"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
		},
	},
}

**Comment by jordonwow** [comment]
Should be fixed in latest version

**Comment by Lintujr** [comment]
Awesome! Thanks dude
