### ISSUE TITLE
Omnibar LUA error on login

### ISSUE THREAD

**Issue by rbrewer3125** [jordonwow/omnibar#32]
When I login I am immediately greeted with this error:

Message: Interface\AddOns\OmniBar\OmniBar.lua:87: attempt to call method 'Initialize' (a nil value)
Time: Sat Oct 19 09:48:41 2019
Count: 1
Stack: Interface\AddOns\OmniBar\OmniBar.lua:87: attempt to call method 'Initialize' (a nil value)
Interface\AddOns\OmniBar\OmniBar.lua:87: in function <Interface\AddOns\OmniBar\OmniBar.lua:70>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...dOns\TitanClassic\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...dOns\TitanClassic\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...dOns\TitanClassic\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:693: in function <Interface\FrameXML\UIParent.lua:658>

Locals: <none>

**Comment by jordonwow** [comment]
Please reopen if you still have this issue with the latest version v10.5
