### ISSUE TITLE
Custom spells

### ISSUE THREAD

**Issue by Johnygreen** [jordonwow/omnibar#34]
Hello, trying to add custom spells to classic omnibar, but it seems i can only add it to only one class.
Trying to add reflectors, free action potion to all classes.

**Comment by holypalaswe** [comment]
I'm having the same issues, finding no way to add multiple classes to same spell. (Same spells as Johnygreen is trying to add; Free Action Potion (6615), Limited Invulnerability Potion (3169) etc.

Wow Classic.

**Comment by mortesd** [comment]
Hey. Have you found a fix for this??
