### ISSUE TITLE
LUA on login

### ISSUE THREAD

**Issue by rbrewer3125** [jordonwow/omnibar#37]
Upon logging in I am greeted with the following:

Message: Interface\AddOns\OmniBar\OmniBar.lua:167: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sat Nov  9 01:04:04 2019
Count: 1
Stack: Interface\AddOns\OmniBar\OmniBar.lua:167: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\OmniBar\OmniBar.lua:167: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

Message: Interface\AddOns\OmniBar\OmniBar.lua:84: attempt to call method 'Initialize' (a nil value)
Time: Sat Nov  9 01:04:08 2019
Count: 1
Stack: Interface\AddOns\OmniBar\OmniBar.lua:84: attempt to call method 'Initialize' (a nil value)
Interface\AddOns\OmniBar\OmniBar.lua:84: in function <Interface\AddOns\OmniBar\OmniBar.lua:70>
[C]: ?
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:693: in function <Interface\FrameXML\UIParent.lua:658>

Locals: <none>

**Comment by mkivtt** [comment]
I get the same error. Addon details:

Date: 2019-11-15 20:44:57
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\OmniBar\OmniBar.lua line 167:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [C]: pairs()
   OmniBar\OmniBar.lua:167: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  BlueShamans, v
  CharacterStatsClassic, v2.6
  ClassicAuraDurations, v
  ClassicCastbars, vv1.1.4
  ClassicCastbarsOptions, v
  ClassicThreatMeter, v1.10
  ColoredInventoryItems, v1.4
  Coordinates, v2.1.0
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DismountMe, v1.5
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GigaAutoResourcesTracker, v0.0.1
  LibStub, v
  OmniBar, vv10.5
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=4b0)

**Comment by jordonwow** [comment]
Please send me your `OmniBar.lua` file found in `WTF/Account/YOUR ACCOUNT/SavedVariables`

**Comment by mkivtt** [comment]
Sure, see attached! I installed the addon out-of-the-box and have never
changed or tweaked anything in its configuration. As soon as I logged in
after installing it, I got this error.

**Comment by jordonwow** [comment]
Can you try v10.6 and let me know if you still experience this issue?

**Comment by mkivtt** [comment]
It seems to work now - I'm not getting any more errors, and can run /ob and
run the test successfully. I'll try to fight someone soon but am not
getting the immediate error upon login anymore. Thanks!
