### ISSUE TITLE
Configuration MENU can't be open

### ISSUE THREAD

**Issue by Kaldrian** [jordonwow/omnibar#38]
Hello there !
I downloaded this add-on but when i'm in the game the /ob command doesn't work and i can't configurate my add-on.

What am i doing wrong ? Thanks by advance

Kaldrian

**Comment by ChristheHed** [comment]
The 10.5 release does not work just like you pointed out above. If you click on Code tab, then go to releases. There you can download release 10.4. I just did and that one works. Hope this helps

**Comment by Kaldrian** [comment]
Still not working. I installed the 10.4 version in the releases and it didn't even shows in my add-ons list.

**Comment by Kaldrian** [comment]
It worked thank you so much !

**Comment by jordonwow** [comment]
I'd like to get this issue fixed so you can use future versions.
Please send me your `OmniBar.lua` file found in `WTF/Account/YOUR ACCOUNT/SavedVariables`
