### ISSUE TITLE
classic defaults

### ISSUE THREAD

**Issue by pmb123** [jordonwow/omnibar#42]
it seems many, many spells are unchecked by default.  Are you still working on creating a default cool downs list for classic?

will you also consider adding alerts for shadow reflector etc?

**Comment by jordonwow** [comment]
Please recommend a list of default spells and I'll consider updating. Currently it's only set to have interrupts as default, and there aren't that many in Classic.

There is a new General category that you can add items like reflectors to. Let me know if you have any issues, thanks.
