### ISSUE TITLE
Player-specific cooldown bar

### ISSUE THREAD

**Issue by vendethiel** [jordonwow/omnibar#51]
Hi,

I was wondering if it'd be possible to have per-player bars. I'm thinking target, focus, arena[123] (and maybe with tweaks to [that line](https://github.com/jordonwow/omnibar/blob/80b5abe54d77f61e022bc6ab12b7cab8a51e71b2/OmniBar.lua#L449), party even).

I looked at the code and I'm not actually sure how to do that... party[123] don't change that often, arena[123] same (it'd be fine to lose their current CDs every time they change, I think), but target could be anything...

So I'm not sure what to do here. If that "target omnibar" is only allowed to be a subset of other bars, then it's fine (we can get the cooldown info back from the "main" bar), but otherwise we need some way to track *all cooldowns from everyone around*.

I guess we could create a "shadow bar" (?) for which `OmniBar_IsSpellEnabled` always returns `true`, and this bar wouldn't be ever shown.
Another solution is to just keep all icons added for "targeted bars", but only show icons relevant to the current unit.

Thoughts?
I'm not afraid to get my hands dirty, but I'd appreciate a pointer. Or maybe you don't even want that feature.

**Comment by jordonwow** [comment]
Great idea and I have added this functionality in the latest release. Thanks.
