### ISSUE TITLE
Tooltip on locked bar

### ISSUE THREAD

**Issue by qrs94** [jordonwow/omnibar#55]
Hello is it possible to make tooltip on locked bar?
It's will be very good option for new players like me that sometime have to remaind them self what spell exacly do. 
From secound hand when its possible to show tooltip on unlocked bars its very easy to move then by mistake.

Best regards,
qrS

**Comment by welpenhund** [comment]
I would like to request this too, seeing the tooltip in the locked window can help a lot sometimes.

**Comment by jordonwow** [comment]
#40
