### ISSUE TITLE
Racials and trinkets

### ISSUE THREAD

**Issue by mortesd** [jordonwow/omnibar#59]
Hey. When creating default spells. I want to add reflectors and racials. But i need to assign these to classes via a dropdown menu. But for instance i want to add escape artist to all gnome classes and reflectors to every class. How do i do this?

**Comment by pmb123** [comment]
hey man.  I don't think it matters.  you can just pick a class, then go to the class and click it to enable it.  now, unless you particularly care when a druid uses reflector and have a separate bar for druids or something like that, then you'd have to make multiple custom spells and add them to each class you want to track.

**Comment by jordonwow** [comment]
There is a General category you can add spells and items like these to now
