### ISSUE TITLE
Bug Premonition tracking - 08/09/2020

### ISSUE THREAD

**Issue by Herazan** [jordonwow/omnibar#67]
Hello, I am contacting you because for a few months now, and despite the fact that the bug has been fixed, I still cannot track the Premonition spell when it is cast by enemies.

I tried uninstalling the addon and reinstalling it but the problem still persists as of 09/08/2020. However, when I use the "test" function of the addon, the icon of the Premonition spell does appear in the list of selected spells, but the latter never appears when an enemy uses it in arenas.

Do you have a solution for me? Thank you

**Comment by jordonwow** [comment]
Please reopen if you experience this issue in v12.0
