### ISSUE TITLE
Missing cd timers

### ISSUE THREAD

**Issue by britziboy** [jordonwow/omnibar#68]
Hey, i miss the cdtimers from omnibar, but why? I used a skin all icons wa that gimme the cdtimers too.
In omnibar options its all fine i think too...
Pls help
![16365E6F-A79B-4DE9-85B9-611BABE88CD9](https://user-images.githubusercontent.com/70173495/91093542-e237b180-e659-11ea-887e-1d4865f4a97f.jpeg)

**Comment by jordonwow** [comment]
Make sure Show numbers for cooldowns is checked in your interface options
