### ISSUE TITLE
Shadowland hiccups 

### ISSUE THREAD

**Issue by l3uGsY** [jordonwow/omnibar#69]
```
Message: Interface\AddOns\OmniBar\Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
Time: Wed Oct 14 18:50:28 2020
Count: 1
Stack: Interface\AddOns\OmniBar\Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
[string "=[C]"]: in function `error'
[string "@Interface\FrameXML\ObjectAPI\Spell.lua"]:51: in function `ContinueOnSpellLoad'
[string "@Interface\AddOns\OmniBar\Options.lua"]:108: in function <Interface\AddOns\OmniBar\Options.lua:53>
[string "@Interface\AddOns\OmniBar\Options.lua"]:557: in function `AddBarToOptions'
[string "@Interface\AddOns\OmniBar\OmniBar.lua"]:104: in function <Interface\AddOns\OmniBar\OmniBar.lua:70>
[string "=[C]"]: ?
[string "@Interface\AddOns\OmniBar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\OmniBar\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\OmniBar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\OmniBar\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:620: in function <...ce\AddOns\OmniBar\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:618: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1373: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>
```

**Comment by rulezxy** [comment]
got the same issue
the addon is working fine unless you dont have a custom setup/profile with multiple bars
also its impossible to change anything /settings

**Comment by aurelion314** [comment]
I made a pull request for the fix, but in the meantime here is what to change, and a link to the download:

Delete this on line 107 in Options.lua: 
```
local s = Spell:CreateFromSpellID(spellID)
s:ContinueOnSpellLoad(function()
	descriptions[spellID] = s:GetSpellDescription()
end
```

Replace with this: 
`descriptions[spellID] = GetSpellDescription(spellID)`

Or download here: [OmniBar.zip](https://github.com/jordonwow/omnibar/files/5395200/OmniBar.zip)

**Comment by rulezxy** [comment]
Ok I changed it. Thank you ;)

**Comment by l3uGsY** [comment]
Thanks, that fixed the issues.

**Comment by Artezian** [comment]
I attempted the fixed written by Aurelion314 and now I cannot access the omnibar menu ui at all. Does this fix work on the twitch version? If not why not? What is the difference between the version on github and the version on twitch?
Thanks.

**Comment by rulezxy** [comment]
@Artezian 
Are you sure you replaced line 107 with: 

descriptions[spellID] = GetSpellDescription(spellID)

You need to delete:

local s = Spell:CreateFromSpellID(spellID)
s:ContinueOnSpellLoad(function()
	descriptions[spellID] = s:GetSpellDescription()
end 

and make sure to have/keep the spacing between the other lines.

You download the addon from curse and change the code in the Options LUA: https://www.curseforge.com/wow/addons/omnibar

It's a quickfix and you won't need more than that. 

We need to wait for SL and Dev's are waiting with alot of updates since alot of spells will be changed/added.

**Comment by dbwtf** [comment]
@rulezxy  So what do this do? Can I configuere inside the omnibar then? I miss the 'lock' buttom, so the omnibar isnt showed all time....

Zzzzz

**Comment by rulezxy** [comment]
@dbwtf 
Yes as already told it's that simple. 
After the quickfix the addon will work as intended.

**Comment by l3uGsY** [comment]
> 
> 
> I made a pull request for the fix, but in the meantime here is what to change, and a link to the download:
> 
> Delete this on line 107 in Options.lua:
> 
> ```
> local s = Spell:CreateFromSpellID(spellID)
> s:ContinueOnSpellLoad(function()
> 	descriptions[spellID] = s:GetSpellDescription()
> end
> ```
> 
> Replace with this:
> `descriptions[spellID] = GetSpellDescription(spellID)`
> 
> Or download here: [OmniBar.zip](https://github.com/jordonwow/omnibar/files/5395200/OmniBar.zip)
