### ISSUE TITLE
shadowlands issue - no options, no customizing

### ISSUE THREAD

**Issue by mashingwarr** [jordonwow/omnibar#70]
93x OmniBar\Options-Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
[string "=[C]"]: in function `error'
[string "@FrameXML\ObjectAPI\Spell.lua"]:51: in function `ContinueOnSpellLoad'
[string "@OmniBar\Options-Options.lua"]:108: in function <OmniBar\Options.lua:53>
[string "@OmniBar\Options-Options.lua"]:557: in function `AddBarToOptions'
[string "@OmniBar\OmniBar-v10.8.lua"]:104: in function <OmniBar\OmniBar.lua:70>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by aurelion314** [comment]
I made a pull request for the fix, but in the meantime here is what to change, and a link to the download:

Delete this on line 107 in Options.lua: 
```
local s = Spell:CreateFromSpellID(spellID)
s:ContinueOnSpellLoad(function()
	descriptions[spellID] = s:GetSpellDescription()
end
```

Replace with this: 
`descriptions[spellID] = GetSpellDescription(spellID)`

Or download here: [OmniBar.zip](https://github.com/jordonwow/omnibar/files/5395200/OmniBar.zip)

**Comment by mashingwarr** [comment]
Hi. Thank you. But what if I am using the twitch app?

**Comment by aurelion314** [comment]
The twitch app won't update until the owner of the addon includes the fix. For now you have to do it manually.

To install it yourself:
Extract [OmniBar.zip](https://github.com/jordonwow/omnibar/files/5395200/OmniBar.zip) into your addon folder. Typically C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\

**Comment by mashingwarr** [comment]
Thank you -- i fixed it. Appreciate your help!
