### ISSUE TITLE
When i creat a new bar i cant customize

### ISSUE THREAD

**Issue by izeross** [jordonwow/omnibar#72]
Hello, im trying to create some bars for customize but i can't.
Simply i can't
![omni](https://user-images.githubusercontent.com/73033235/96348306-02a74980-10a8-11eb-9452-979651bea70f.jpg)

**Comment by gaveer** [comment]
@izeross   Make sure omnibar option is running

**Comment by vladskii** [comment]
Same problem with me

**Comment by PraddaG** [comment]
Was trying to help a friend troubleshoot a problem with Omnibar, now I see I have this same issue. Can't change visibility, can't delete extra bars without just resetting the profile. At a loss.

**Comment by PraddaG** [comment]
So there's another post below this one. If you delete Omnibar as is from your addons, https://github.com/jordonwow/omnibar/files/5395200/OmniBar.zip download this and drag it into your addon folder. Problem solved.

**Comment by Seananon** [comment]
Problem solved. Thanks PraddaG
