### ISSUE TITLE
 omnibar Locked + show spell tooltip = no tooltips displayed

### ISSUE THREAD

**Issue by Ahazu77** [jordonwow/omnibar#74]
Setting as it is in the title, nothing is shown, but when setting the omnibar bar unlocked, the spell tooltips are shown

**Comment by Kennah229** [comment]
Working as intended. If the bar is locked, you can't see the tooltips. Has to be unlocked to show tooltips.

**Comment by Ahazu77** [comment]
ok, there's no other way to enable the tooltips when bar is locked?

**Comment by djschalk** [comment]
Any way you can change this then if that is the intention? It is a very frustrating combination. If I want to read what the spells do, I have 5 bars that may be accidentally right clicked and moved all around. I would like my bar to be locked and have the ability to read what spells do.

**Comment by jordonwow** [comment]
#40
