### ISSUE TITLE
omnibar no bars to configure

### ISSUE THREAD

**Issue by ISTmiguel** [jordonwow/omnibar#75]
hello,

i dont see any bars to configure, I can create bars but there is nothing to configure.. i dont see the omnibar 1 2 3 or 4 in the menus.. 
i tried deleting some files, reinstalling.. nothing works

this is my LUA errror

Message: Interface\AddOns\OmniBar\Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
Time: Mon Oct 26 18:42:18 2020
Count: 1
Stack: Interface\AddOns\OmniBar\Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `error'
[string "@Interface\FrameXML\ObjectAPI\Spell.lua"]:51: in function `ContinueOnSpellLoad'
[string "@Interface\AddOns\OmniBar\Options.lua"]:108: in function <Interface\AddOns\OmniBar\Options.lua:53>
[string "@Interface\AddOns\OmniBar\Options.lua"]:557: in function `AddBarToOptions'
[string "@Interface\AddOns\OmniBar\OmniBar.lua"]:104: in function <Interface\AddOns\OmniBar\OmniBar.lua:70>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>
Message: Interface\AddOns\OmniBar\Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
Time: Mon Oct 26 18:42:18 2020
Count: 1
Stack: Interface\AddOns\OmniBar\Options.lua:108: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `error'
[string "@Interface\FrameXML\ObjectAPI\Spell.lua"]:51: in function `ContinueOnSpellLoad'
[string "@Interface\AddOns\OmniBar\Options.lua"]:108: in function <Interface\AddOns\OmniBar\Options.lua:53>
[string "@Interface\AddOns\OmniBar\Options.lua"]:557: in function `AddBarToOptions'
[string "@Interface\AddOns\OmniBar\OmniBar.lua"]:104: in function <Interface\AddOns\OmniBar\OmniBar.lua:70>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by grigorasmihai** [comment]
@ISTmiguel  check https://github.com/jordonwow/omnibar/issues/73
