### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by Hellswake** [jordonwow/omnibar#8]
Downloaded Omnibar today, when I click on most things inside on the options panel I get LUA errors. Clicking on the spells list gives this one below. Can anyone help with this?

Message: Interface\AddOns\OmniBar\Options.lua:120: bad argument #2 to 'format' (string expected, got nil)
Time: Wed Dec 12 13:44:23 2018
Count: 1
Stack: Interface\AddOns\OmniBar\Options.lua:120: bad argument #2 to 'format' (string expected, got nil)
[C]: in function `format'
Interface\AddOns\OmniBar\Options.lua:120: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:220: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:168>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:342: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:315>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:959: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:955>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1012: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:989>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1670: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1508: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1492>
[C]: ?
...erface\AddOns\OmniBar\Libs\AceGUI-3.0\AceGUI-3.0.lua:71: in function <...erface\AddOns\OmniBar\Libs\AceGUI-3.0\AceGUI-3.0.lua:69>
...erface\AddOns\OmniBar\Libs\AceGUI-3.0\AceGUI-3.0.lua:285: in function `Fire'
...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:156: in function `SelectTab'
...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:67: in function <...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

Locals: <none>

**Comment by Gee19** [comment]
See #6 for a temporary fix or wait until it's fixed upstream.

**Comment by Hellswake** [comment]
> See #6 for a temporary fix or wait until it's fixed upstream.

Thank you, ehh I will just wait for it to be fixed on the upstream, I don't know enough about programming and will probably melt my computer. =) thank you for the reply tho.

**Comment by Gee19** [comment]
You should be able to just download a zip version of my fork and install it as you would any other addon :)

https://github.com/Gee19/omnibar/archive/master.zip

**Comment by jordonwow** [comment]
Thank you @Gee19
