### ISSUE TITLE
Options missing, no fix works

### ISSUE THREAD

**Issue by Markcba** [jordonwow/omnibar#87]
Hi,

I can't seem to get the options tab to show, I have tried the solution in #73 to replace the retail.lua file, and the solution in #70 to replace line 107 in the options.lua file, and also both together, nothing seems to work. 
I would like very much to be able to fix my bars and keep on playing with omnibar, since I feel there isn't a valid alternative atm.
Any help would be greatly appreciated, thanks in advance.

**Comment by Metsz** [comment]
This is an issue for me aswell. I would love a fix or an update to get omnibar to work again. I've tried many reinstalls and also replacing the original files with files containing the "fix". Anyone who can share information of how to get it to work would be appreciated!

**Comment by Metsz** [comment]
Also, the bars are not showing inside arena or any other place they are checked to be visible. Thanks in advance!

**Comment by Markcba** [comment]
For anyone who might still have this problem, I found a fix that worked for me:
I went here "https://github.com/Gee19/omnibar/archive/master.zip" and downloaded this guy's modified files, then copied them in my /_retail_/Interface/Addons/OmniBar folder. Everything works fine now. Hope it works for you aswell.
