### ISSUE TITLE
Addon confusing enemy spec in battlegrounds

### ISSUE THREAD

**Issue by hemirocks** [jordonwow/omnibar#96]
Tested in rated battlegrounds, dont know about randoms. For example we got a fire mage on enemy team and if I am tracking both Icy Veins and Combustion, the addon shows both the cooldowns. In arena there is no spec confusion. Working as intended. Also it tracks Ascendance for elemental shamans even if they havent picked the talent. Same thing not happening in arenas. Also Ascendance tracking in the spells must be differenatited for all shaman specs. All 3 specs has their own spell ID for Ascendace and it doesnt allow me to add spec spesific Ascendance spells because it has one. But still spec confusing in the bgs is a bigger problem.

**Comment by jordonwow** [comment]
Please reopen if you experience this issue in v12.0
