### ISSUE TITLE
Omni bar not shwoing enemy CDs

### ISSUE THREAD

**Issue by Firewinf** [jordonwow/omnibar#97]
After todays updates, OB is not showing me enemy cds, only its default interrupts.
Any idea why this is happening?
thx!

**Comment by Exupery** [comment]
I'm experiencing similar, it's only showing interrupts (despite being configured to show far more) but even then only some, e.g. I just faced mage/rogue in 2s and it showed the rogue's kick but not the mage's counterspell.

**Comment by vasade** [comment]
Same here, except I can't see anything after the update

**Comment by r3medy** [comment]
Similar issues here. Had reports from multiple friends/pvp discords of the same issue, though many don't use GitHub.

**Comment by gonzric1** [comment]
I had the same problem and figured it out. There's a new tab for each bar called "units". None are checked by default. Make sure to check them and the cds show up again.

**Comment by maki-prog** [comment]
Thanks @gonzric1, this solved my issue! I suppose it was intended then.

**Comment by scorpgul** [comment]
> 
> 
> I had the same problem and figured it out. There's a new tab for each bar called "units". None are checked by default. Make sure to check them and the cds show up again.

THIS! OMG I was going crazy trying to figure out why my bars were not working. thanks a lot mate!

**Comment by jordonwow** [comment]
Please reopen if you experience this issue on the latest version.
