### ISSUE TITLE
OmniBar doesn't show any CDs in the arena

### ISSUE THREAD

**Issue by eyalsk** [jordonwow/omnibar#99]
I have no idea what's going on but for few versions now I can't see any of the enemies CDs, I DO have "Show in Arena" and "Enable All Enemies" checked. 

I can post my Saved Variables if it helps.

I'd love some guidance if possible because I'm at a loss.

**Comment by Kakattack** [comment]
I have the same issue.

**Comment by scorpgul** [comment]
Same issue here. This is terrible, makes the addon pretty much useless

**Comment by KakaduMate** [comment]
I managed to fix it by going under 'Units' and ticking enable all.

I then went into curseforge and selected reinstall add-on.

Hopes this works for you guys 🙂

**Comment by eyalsk** [comment]
@KakaduMate I have "Enable All Enemies" checked... I don't think that reinstalling is going to help if the code is exactly the same.

**Comment by KakaduMate** [comment]
Yeah my code wasn't altered I just hit reinstall anyway and it worked. Figured it's better to try then not.

**Comment by eyalsk** [comment]
@KakaduMate Sure but if I had to guess it wasn't because you reinstalled it's because you checked "Enable All Enemies" mine is already checked and it still doesn't work so there might be a bug that causes this.

**Comment by KakaduMate** [comment]
Nope, tested it in a skirmish after ticking enable all enemies. Then tested again after reinstall and it worked. It's worth an attempt.

**Comment by eyalsk** [comment]
@KakaduMate Interesting.

**Comment by eyalsk** [comment]
I've checked the code and it seems like "Enable All Enemies" does nothing for the arena and you actually have to check "Enable Arena 1" , "Enable Arena 2" and "Enable Arena 3" for the spells to show up in the arena. Not confusing at all. :D
